---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:
    
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present